# Native Image 构建配置
# GraalVM Native Image 构建参数，替代 pom.xml 中的 buildArgs

Args = --no-fallback \
       -H:+ReportExceptionStackTraces \
       --enable-url-protocols=http,https \
       --initialize-at-build-time=org.slf4j.LoggerFactory \
       --enable-all-security-services